config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    invitations: "users/invitations" }

  get "users/:id" => "users#show", as: :user
  get "/otp_entry" => "home#otp_entry", as: :otp_entry
  post "/verify_otp" => "home#verify_otp", as: :verify_otp

  devise_scope :user do
    get "/sign-in" => "devise/sessions#new", :as => :login
  end

  resources :users, only: %i[index] do
    member do
      patch :lock_or_unlock
      patch :resend
      delete :destroy
      get :dashboard
      patch :enable_otp
      patch :disable_otp
      patch :issue_api_token
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#welcome"

  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount API::Base, at: '/'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :lockable, :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :two_factor_authenticatable

  validates :email, presence: true, uniqueness: true, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :mobile_phone, presence: true, uniqueness: true, on: :create
  validates :time_zone, presence: true, on: :create

  attr_accessor :user_role_id
  attr_reader :raw_invitation_token

  delegate :can?, :cannot?, to: :ability

  def ability
    @ability ||= Ability.new(self)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    has_role? :SYS_ADMIN
  end

  def user?
    has_role? :SYS_USER
  end

  def requires_2fa?
    roles.each do |role|
      return true if role.requires_2fa?
    end
    false
  end

  def masked_email
    return email if email.length <= 8

    # Mask middle characters except '@'
    masked = email.chars.each_with_index.map do |char, i|
      if i < 4 || i >= email.length - 4 || char == "@"
        char
      else
        "*"
      end
    end

    masked.join
  end

  def role_names
    roles.collect(&:name).join(", ")
  end

  def role_desc
    role_desc_str = ""
    roles.each do |role|
      role_desc_str = "#{role_desc_str}, #{role.description}"
    end
    role_desc_str[2..]
  end

  def generate_token(current_user)
    if raw_invitation_token.nil?
      self.invite!(current_user) do |u|
        u.skip_invitation = true
      end
    end
  end

  def send_new_user_email(current_user)
    # Generate a new token for the user
    generate_token(current_user)

    if user?
      WelcomeMailer.with(user: self, raw_token: raw_invitation_token).new_user_email.deliver_later
      # SendNewUserEmailJob.perform_later(self, raw_invitation_token)
    elsif admin?
      WelcomeMailer.with(user: self, raw_token: raw_invitation_token).new_admin_email.deliver_later
      # SendNewAdminEmailJob.perform_later(self, raw_invitation_token)
    end
  end

  def send_otp_email
    otp_code = current_otp
    WelcomeMailer.with(user: self, otp_code: otp_code).verification_email.deliver_later
  end

  def self.admin_users
    User.with_role(:SYS_ADMIN).where(active: true)
  end

  def self.search(search_name, search_role)
    search_name = "" if search_name.nil?
    search_role = "" if search_role.nil?

    sql = "
      select distinct usr.*
        from users usr
       inner join users_roles url
          on url.user_id = usr.id
       inner join roles rol
          on rol.id = url.role_id
         and rol.name like '%#{search_role}%'
       where lower(concat(usr.first_name, usr.last_name)) like '%#{search_name.downcase}%'
         and usr.active = true
       order by usr.last_name
           , usr.first_name"

    find_by_sql(sql)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  include UsersHelper
  def new
    @user_role = Role.find_by(name: params[:user_role_id])
    @page_title = "New #{@user_role.description}"
    @submit_label = "Invite #{@user_role.description}"
    super
  end

  def create
    user_role = Role.find_by(name: invite_params[:user_role_id])
    notice = nil

    existing_user = User.find_by(email: invite_params[:email])
    user = nil

    if existing_user.present?
      user = existing_user
      notice = "User with email #{user.email} already exists, just adding #{user_role.description} role to the user."
    else
      user = User.new(email: invite_params[:email],
                      first_name: invite_params[:first_name],
                      last_name: invite_params[:last_name],
                      mobile_phone: invite_params[:mobile_phone],
                      created_by: invite_params[:created_by],
                      updated_by: invite_params[:updated_by])

      notice = "Invitation sent to #{user.email}, roles and relationships added."
    end

    user.add_role(user_role.name) unless user.has_role? user_role.name
    user.send_new_user_email(current_user)

    redirect_to users_path, notice:
  end

  def update
    super
    # set this session parameters after accepting the passwords
    session[:user_email] = @user.email
    session[:user_role] = @user.role_desc

    return unless @user.requires_2fa?

    # Force enabling OTP for the user if their role requires 2FA
    enable_otp_for_user(@user)
  end

  private

  def update_resource_params
    params.require(:user).permit(:password, :password_confirmation, :user, :email, :invitation_token, :updated_by)
  end

  # This is called when creating invitation.
  # It should return an instance of resource class.
  def invite_resource
    # skip sending emails on invite
    super { |user| user.skip_invitation = true }
    # super
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  ADMIN_ROLE = "SYS_ADMIN"
  ATTRIBUTES = %i[first_name last_name email mobile_phone created_by updated_by]

  before_action :configure_sign_up_params, only: [ :create ]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if @user.save
      @user.add_role(ADMIN_ROLE)

      session[:user_email] = @user.email
      session[:user_role] = @user.role_desc
    end
    if @user.requires_2fa?
      enable_otp_for_user(@user)
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: ATTRIBUTES)
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: ATTRIBUTES)
    end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options.merge(strategy: :password_authenticatable))

    return unless resource&.active_for_authentication?

    if resource.otp_required_for_login
      resource.send_otp_email
      sign_out(resource)
      session[:otp_token] = resource.id
      redirect_to otp_entry_path, notice: "Two-factor authentication code required"
    else
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
    session.clear
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  include UsersHelper

  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_user, only: %i[show dashboard lock_or_unlock resend destroy disable_otp enable_otp]
  before_action :set_tabs, only: %i[show dashboard]


  def index
    search_name = (params[:search_name] if params[:search_name] && !params[:search_name].empty?)
    search_role = (params[:search_role] if params[:search_role] && !params[:search_role].empty?)

    @users = User.search(search_name, search_role)
  end

  def show
  end

  def dashboard
  end

  def lock_or_unlock
    notice_text = nil
    if @user.access_locked?
      @user.unlock_access!
      notice_text = "unlocked"
    else
      @user.lock_access!
      notice_text = "locked"
    end
    redirect_to users_path, notice: "User #{@user.email} access #{notice_text}"
  end

  def resend
    if @user.created_by_invite? && @user.invitation_accepted? == false
      @user.send_new_user_email(current_user)
      redirect_to users_path, notice: "User #{@user.email} re-invited"
    else
      redirect_to users_path, alert: "User #{@user.email} already active"
    end
  end

  def destroy
    @user.active = false
    @user.save
    redirect_to users_path, notice: "User was successfully deleted."
  end

  def disable_otp
    disable_otp_for_user(@user)
    redirect_to users_path, notice: "Two-factor authentication disabled"
  end

  def enable_otp
    enable_otp_for_user(@user)
    redirect_to users_path, notice: "Two-factor authentication enabled"
  end

  def issue_api_token
    @user.update!(api_token: SecureRandom.hex(32))
    redirect_to request.referer, notice: "API token issued: #{@user.api_token}. Use this token for authenticating API requests."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_tabs
    @users_all = User.all
    @users_active = User.where(active: true)
    @users_inactive = User.where(active: false)

    tabs = { users_all: { label: "All",
                          render: "users",
                          dataset: @users_all,
                          parent: @user,
                          source: "user" },
             users_active: { label: "Active",
                             render: "users",
                             dataset: @users_active,
                             parent: @user,
                             source: "user" },
             users_inactive: { label: "Inactive",
                               render: "users",
                               dataset: @users_inactive,
                               parent: @user,
                               source: "user" } }

    @bootstrap_tabs = BootstrapTabs.new(tabs, current_user, params)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def disable_otp_for_user(user)
    user.otp_required_for_login = false
    user.save!
  end

  def enable_otp_for_user(user)
    user.otp_secret = User.generate_otp_secret
    user.otp_required_for_login = true
    user.save!
  end

  def populate_otp_fields_for_users
    User.all.each do |user|
      next unless user.requires_2fa? && !user.otp_required_for_login?

      p "Enabling 2FA for user #{user.email} as their role requires 2FA"
      enable_otp_for_user(user)
    end
  end
end

app/views/users/_user.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= user.full_name %></h5>
    <div class="card-text">
      <table class="table table-striped table-hover table-sm">
        <tr>
          <th>Email</th>
          <td><%= user.email %></td>
        </tr>
        <tr>
          <th>Phone</th>
          <td><%= user.mobile_phone %></td>
        </tr>
        <% if can? :lock_or_unlock, user %>
          <tr>
            <th>Access</th>
            <td><%= render "layouts/icons_helper", field_value: user.access_locked?, field_type: "lock" %></td>
          </tr>
        <% end %>
        <% if can?(:resend, user) && user.created_by_invite? %>
          <tr>
            <th><span class="d-none d-md-inline">Invitation </span>Accepted</th>
            <td><%= render "layouts/icons_helper", field_value: user.invitation_accepted?, field_type: "yes_no" %></td>
          </tr>
        <% end %>
        <tr>
          <th>Roles</th>
          <td><%= user.role_desc %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
<% users = collection %>
<% unless users.empty? %>
  <% if source == 'index' %>
    <% users = Kaminari.paginate_array(users).page(params[:page]) %>
  <% end %>
  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th>Name</th>
        <th class="d-none d-md-table-cell">Email</th>
        <th class="d-none d-lg-table-cell">Mobile</th>
        <th>Roles</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td>
            <% if current_user.can? :read, user %>
              <%= link_to user.full_name, url.user_path(user) %>
            <% else %>
              <%= user.full_name %>
            <% end %>
          </td>
          <td class="d-none d-md-table-cell"><%= user.email %></td>
          <td class="d-none d-lg-table-cell"><%= user.mobile_phone %></td>
          <td><%= user.role_desc %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if source == 'index' %>
    <% if users.total_pages > 1 %>
      <div class="container small">
        <div class="row text-center my-3">
          <div class="col">
            <%= paginate users %>
            <%= page_entries_info users %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/dashboard.html.erb
<%= render 'layouts/page_title', page_title: 'Dashboard', page_subtitle: nil %>
<div class="container border shadow bg-light bg-gradient">
  <div class="row my-3">
    <div class="col text-center">
      To come ...
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/page_title', page_title: 'Users', page_subtitle: nil %>
<div class="container border shadow bg-light bg-gradient">
  <div class="row my-3">
    <div class="accordion" id="accordionSearch">
      <div class="accordion-item">
        <h5 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Search
          </button>
        </h5>
        <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionSearch">
          <div class="accordion-body">
            <%= form_tag users_path, method: :get do %>
              <div class="container">
                <div class="row my-3">
                  <div class="col-md-3 text-md-end">
                    <%= label_tag "Name" %>
                  </div>
                  <div class="col-md">
                    <%= text_field_tag :search_name, params[:search_name], class: "form-control" %>
                  </div>
                </div>
                <div class="row my-3">
                  <div class="col-md-3 text-md-end">
                    <%= label_tag "User role" %>
                  </div>
                  <div class="col-md">
                    <%= select_tag :search_role, options_from_collection_for_select(user_role_codes, "code", "code_desc"), include_blank: true, class: "form-select" %>
                  </div>
                </div>
                <div class="row my-3">
                  <div class="col-md-6 d-grid my-3">
                    <%= button_tag(class: "btn btn-primary") do %>
                      <i class="fi-magnifying-glass"></i>&nbsp;Search
                    <% end %>
                  </div>
                  <div class="col d-grid my-3">
                    <%= link_to users_path, class: "btn btn-primary" do %>
                      <i class="fi-list"></i>&nbsp;Clear
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-md-9 col-lg-10 order-md-1 order-2">
      <%= render 'users', collection: @users, source: 'index', url: Rails.application.routes.url_helpers, current_user: current_user %>
    </div>
    <div class="col-md-3 col-lg-2 order-md-1 order-2">
      <% if can? :create, User %>
        <% if current_user.admin? %>
          <div class="d-grid my-3">
            <%= link_to new_user_invitation_path(user_role_id: "SYS_ADMIN"), class: "btn btn-primary" do %>
              <i class="fi-plus"></i>&nbsp;New admin
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/page_title', page_title: 'User', page_subtitle: nil %>
<div class="container border shadow bg-light bg-gradient">
  <div class="row my-3">
    <div class="col-md-9 col-lg-10 order-md-1 order-2">
      <div class="d-grid my-3">
        <%= render @user, user: @user, summary: true %>
      </div>
    </div>
    <div class="col-md-3 col-lg-2 order-md-1 order-2">
      <% if @user.id == current_user.id %>
        <div class="d-grid my-3">
          <%= link_to edit_user_registration_path, class: "btn btn-primary" do %>
            <i class="fi-pencil"></i>&nbsp;Edit
          <% end %>
        </div>
      <% end %>
      <% if can?(:resend, @user) && @user.created_by_invite? %>
        <% unless @user.invitation_accepted? %>
          <%= button_to resend_user_path(@user), {method: :patch, form_class: "d-grid my-3", class: "btn btn-primary"} do %>
            <i class="fi-mail"></i>&nbsp;Resend Invite
          <% end %>
        <% end %>
      <% end %>
      <% if can?(:lock_or_unlock, @user) && @user.id != current_user.id %>
        <% if @user.access_locked? %>
          <%= button_to lock_or_unlock_user_path(@user), {method: :patch, form_class: "d-grid my-3", class: "btn btn-primary"} do %>
            <i class="fi-unlock"></i>&nbsp;Unlock
          <% end %>
        <% else %>
          <%= button_to lock_or_unlock_user_path(@user), {method: :patch, form_class: "d-grid my-3", class: "btn btn-primary"} do %>
            <i class="fi-lock"></i>&nbsp;Lock
          <% end %>
        <% end %>
      <% end %>
      <% if can? :issue_api_token, @user %>
        <%= button_to issue_api_token_user_path(@user), {method: :patch, form_class: "d-grid my-3", class: "btn btn-primary"} do %>
          <i class="fi-key"></i>&nbsp;Issue API Token
        <% end %>
      <% end %>
      <% if can?(:delete, @user) && @user.id != current_user.id %>
        <%= button_to user_path(@user), {data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, form_class: "d-grid my-3", class: "btn btn-danger"} do %>
          <i class="fi-trash"></i>&nbsp;Delete
        <% end %>
      <% end %>
      <div class="d-grid my-3">
        <%= link_to users_path, class: "btn btn-secondary" do %>
          <i class="fi-previous"></i>&nbsp;Users
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render 'layouts/bootstrap_tabs', bootstrap_tabs: @bootstrap_tabs %>
  </div>
</div>