config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    invitations: "users/invitations" }

  get "users/:id" => "users#show", as: :user
  get "/otp_entry" => "home#otp_entry", as: :otp_entry
  post "/verify_otp" => "home#verify_otp", as: :verify_otp

  devise_scope :user do
    get "/sign-in" => "devise/sessions#new", :as => :login
  end

  resources :users, only: %i[index] do
    member do
      patch :lock_or_unlock
      patch :resend
      delete :destroy
      get :dashboard
      patch :enable_otp
      patch :disable_otp
      patch :issue_api_token
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#welcome"

  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount API::Base, at: '/'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, only: %i[otp_entry verify_otp]

  def welcome
    if user_signed_in?
      redirect_to dashboard_user_path(current_user)
    else
      render "welcome"
    end
  end

  def otp_entry; end

  def verify_otp
    if @user.validate_and_consume_otp!(params[:otp_attempt])
      sign_in(@user)
      session.delete(:otp_token)
      redirect_to after_sign_in_path_for(@user), notice: "Signed in successfully."
    else
      redirect_to login_path, alert: "Invalid two-factor code, please sign-in again."
    end
  end

  private

  def set_user
    @user = User.find(session[:otp_token]) if session[:otp_token]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/otp_entry.html.erb
<%= render 'layouts/page_title', page_title: "Verification Code Entry", page_subtitle: nil %>
<div class="container border shadow bg-light bg-gradient">
  <%= form_with url: verify_otp_path, method: :post do |form| %>
    <div class="row my-3">
      <div class="col-md-9 col-lg-10 order-md-1 order-2">
        <div class="row my-3">
          <div class="col-md">
            <h5>Check your Email</h5>
          </div>
        </div>
        <div class="row my-3">
          <div class="col-md">
            A verification code was sent to <strong><%= @user.masked_email %></strong>.
          </div>
        </div>
        <div class="row my-3">
          <div class="col-md-3 text-md-end">
            <%= form.label 'Verification code', class: "form-label" %>
          </div>
          <div class="col-md">
            <%= form.text_field :otp_attempt, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-lg-2 order-md-1 order-2">
        <div class="d-grid my-3">
          <%= button_tag class: "btn btn-primary" do %>
            <i class="fi-unlock"></i>&nbsp;Authenticate
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/welcome.html.erb
<%= render 'layouts/page_title', page_title: "Welcome", page_subtitle: nil %>
<% unless SystemCode.any? %>
  <div class="alert alert-danger" role="alert">
    <strong>Setup not Complete. </strong><br>
    Load static data by running rails db:seed.
  </div>
<% else %>
  <div class="container border shadow bg-light bg-gradient">
    <div class="row my-3">
      <div class="col text-center">
        <%= image_tag WELCOME_IMAGE %>
      </div>
    </div>
  </div>
<% end %>