config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    invitations: "users/invitations" }

  get "users/:id" => "users#show", as: :user
  get "/otp_entry" => "home#otp_entry", as: :otp_entry
  post "/verify_otp" => "home#verify_otp", as: :verify_otp

  devise_scope :user do
    get "/sign-in" => "devise/sessions#new", :as => :login
  end

  resources :users, only: %i[index] do
    member do
      patch :lock_or_unlock
      patch :resend
      delete :destroy
      get :dashboard
      patch :enable_otp
      patch :disable_otp
      patch :issue_api_token
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#welcome"

  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount API::Base, at: '/'
end

app/views/layouts/_bootstrap_tabs.html.erb
<% unless bootstrap_tabs.is_empty? %>
  <div class="row my-3">
    <div class="col">
      <ul class="nav nav-tabs" id="bootstrapTab" role="tablist">
        <%= bootstrap_tabs.render_tab_header.html_safe %>
      </ul>
      <div class="tab-content" id="bootstrapTabContent">
        <%= bootstrap_tabs.render_tab_body.html_safe %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if current_model.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong><%= pluralize(current_model.errors.count, "error") %> prohibited this record from being saved:</strong>
    <ul>
      <% current_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row text-muted">
    <div class="col">
      <small><%= session[:user_role] %></small>
    </div>
    <div class="col text-end">
      <small>Powered by <a href="http://computability.com.au/">Computability</a></small>
    </div>
  </div>
</div>

app/views/layouts/_icons_helper.html.erb
<% field = field_value.to_s.downcase %>
<% if field_type == "lock" %>
  <% if field == "true" %>
    <i class="fi-lock" style="color:red"></i>
  <% else %>
    <i class="fi-unlock" style="color:green"></i>
  <% end %>
<% else %>
  <% case field %>
  <% when "true" %>
    <i class="fi-check" style="color:green"></i>
  <% when "false" %>
    <i class="fi-x" style="color:red"></i>
  <% when "full" %>
    <i class="fi-checkbox" style="color:green"></i>
  <% when "restricted" %>
    <i class="fi-alert" style="color:orange"></i>
  <% when "none" %>
    <i class="fi-prohibited" style="color:red"></i>
  <% when "rating" %>
    <% score.to_i.times do %>
      <i class="fi-star"></i>
    <% end %>
    <% remaining = (defined?(limit) ? limit.to_i : 5) - score.to_i %>
    <span style="opacity:10%">
      <% remaining.times do %>
        <i class="fi-star"></i>
      <% end %>
    </span>
  <% else %>
    <i class="fi-info" style="color:blue"></i>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark navbar-expand-md bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%# <%= link_to image_tag("logo_long_transparent_25"), root_path, class: "navbar-brand" %>
    <%= link_to image_tag(NAVBAR_LOGO), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= render "layouts/navlinks" %>
    </div>
  </div>
</nav>

app/views/layouts/_navlinks.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
    <%= link_to root_path, class: "nav-link active", aria: {current: "page"} do %>
      <span class="fi-home"></span> Home
    <% end %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to users_path, class: "nav-link" do %>
        <span class="fi-torsos-all"></span> Users
      <% end %>
    </li>
  <% end %>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li class="nav-item">
    <% if User.any? %>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="fi-torso"></span>&nbsp; <%= session[:user_email] %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <span class="fi-torso"></span> Profile
              <% end %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
                <span class="fi-eject"></span> Sign Out
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <%= link_to login_path, class: "nav-link" do %>
          <span class="fi-play"></span> Sign In
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_registration_path, class: "nav-link" do %>
        <span class="fi-torso"></span> Set Admininstrator
      <% end %>
    <% end %>
  </li>
</ul>

app/views/layouts/_page_title.html.erb
<div class="container">
  <div class="row my-3">
    <h4 class="text-center"><%= page_title %></h4>
    <% if (page_subtitle.present?) then %>
      <h5 class="text-center"><%= page_subtitle %></h5>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= APP_SHORT_NAME %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/801e4a4dd6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "foundation-icons" %>
    <%= stylesheet_link_tag "actiontext" %>
    <%= stylesheet_link_tag "simple-calendar" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="apple-touch-icon" href="<%= FAVICON_LOGO %>">
    <%= favicon_link_tag FAVICON_LOGO %>
    <%= yield :head %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "layouts/navbar" %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>